# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" 
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      # Check for updates at 9 in the morning just before we start working
      time: "08:00"
      # Use Copenhagen Standard Time (UTC +09:00)
      timezone: Europe/Copenhagen
    # prefix all commit messages with pip
    # to pip against the `dependabot-updates` branch
    target-branch: "dependabot-updates"
    commit-message:
      prefix: "pip"

      
      
      
  - package-ecosystem: "npm"
    directory: "/traffic_speed_prediction/frontend"
    schedule:
      interval: "daily"
      # Check for updates at 9 in the morning just before we start working
      time: "08:00"
      # Use Copenhagen Standard Time (UTC +09:00)
      timezone: Europe/Copenhagen
    # to pip against the `dependabot-updates` branch
    target-branch: "dependabot-updates"
    commit-message:
      # Prefix all commit messages with "npm"
      prefix: "npm"
