version: '3.9'

volumes:
  db_data:

services:

  app:
    image: ghcr.io/denizisik58/tsp:latest
    volumes:
      - .:/app
    restart: always
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 traffic_speed_prediction/manage.py makemigrations
      && python3 traffic_speed_prediction/manage.py migrate
      && python3 traffic_speed_prediction/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  shepherd:
    image: mazzolino/shepherd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      IMAGE_AUTOCLEAN_LIMIT: 3
      IGNORELIST_SERVICES: 'tsp_shepherd tsp_db'
      TZ: Europe/Copenhagen
    deploy:
      placement:
        constraints:
          - node.role == manager
