version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=testdb
    ports:
      - '5432:5432'
  
  traffic_speec_prediction:
    build: .
    volumes:
      - .:/app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: testdb
    command: >
      sh -c "python3 traffic_speed_prediction/manage.py makemigrations
      && python3 traffic_speed_prediction/manage.py migrate
      && python3 traffic_speed_prediction/manage.py runserver"

volumes:
  db:
    driver: local