version: '3.9'

services:
  app:
    build: .
    container_name: TSP
    volumes:
      - .:/app
    restart: always
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 traffic_speed_prediction/manage.py makemigrations
      && python3 traffic_speed_prediction/manage.py migrate
      && StartApplication.ps1"
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - "5432:5432"

volumes:
  postgres_data:

