version: '3.9'

services:
  traffic_speec_prediction:
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./.:/app
    command: >
      sh -c "python3 traffic_speed_prediction/manage.py runserver"