version: '3.9'

volumes:
  db_data:

services:
  frontend:
    image: ghcr.io/denizisik58/frontend:latest
    restart: always
    ports:
      - "3000:3000"
    command: >
      sh -c "npm start"

  app:
    image: ghcr.io/denizisik58/tsp:latest
    restart: always
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 traffic_speed_prediction/manage.py migrate
      && python3 traffic_speed_prediction/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    deploy:
        mode: replicated
        replicas: 3

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

  shepherd:
    image: mazzolino/shepherd
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SLEEP_TIME: 3600
      IMAGE_AUTOCLEAN_LIMIT: 3
      IGNORELIST_SERVICES: 'tsp_shepherd tsp_db'
      TZ: Europe/Copenhagen
    deploy:
      placement:
        constraints:
          - node.role == manager
