version: '3.9'

services:
  tsp:
    build: .
    container_name: TSP
    volumes:
      - .:/app
    env_file:
      - ./.env
    restart: always
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 traffic_speed_prediction/manage.py makemigrations
      && python3 traffic_speed_prediction/manage.py migrate
      && python3 traffic_speed_prediction/manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:

