name: Frontend Image Continous Deployment

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_ACCESS_TOKEN }}

      - name: Build and Push frontend Image
        uses: docker/build-push-action@v2
        with:
          context: Frontend/reactjs/Dockerfile
          push: true
          tags: |
            ghcr.io/denizisik58/frontend:latest